name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
   #  - uses: cachix/cachix-action@v12
   #    with:
   #      name: gtfs-onboarding
   #      authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
